export enum Actions {
  PRODUCTS_FILTER = 'PRODUCTS_FILTER',
  PRODUCTS_SORT = 'PRODUCTS_SORT',
  PRODUCTS_SWITCH_VIEW = 'PRODUCTS_SWITCH_VIEW',
  PRODUCT_ADD_TO_CART = 'PRODUCT_ADD_TO_CART',
  PRODUCT_DROP_FROM_CART = 'PRODUCT_DROP_FROM_CART',
  PRODUCT_BUY = 'PRODUCT_BUY',
}
