export enum Actions {
  APPLY_PRODUCT_FILTER = 'APPLY_PRODUCT_FILTER',
  APPLY_PRODUCTS_SORT = 'APPLY_PRODUCTS_SORT',
  APPLY_PRODUCTS_SWITCH_VIEW = 'APPLY_PRODUCTS_SWITCH_VIEW',
  PRODUCT_ADD_TO_CART = 'PRODUCT_ADD_TO_CART',
  PRODUCT_DROP_FROM_CART = 'PRODUCT_DROP_FROM_CART',
  PRODUCT_BUY = 'PRODUCT_BUY',
  PRODUCT_DROP_IN_LAST_CART_PAGE = 'PRODUCT_DROP_IN_LAST_CART_PAGE',
}
